import numpy as np

from ase.neighborlist import NeighborList, natural_cutoffs


def build_neighbor_network(
    atoms,
    cutoff_scale=1.20,
):
    """
    Build the first-neighbor network of a finite nanoparticle.

    Candidate neighbors are identified using ASE covalent radii.
    The nanoparticle is treated as a non-periodic finite structure.

    Parameters
    ----------
    atoms : ase.Atoms
        Finite crystalline nanoparticle.

    cutoff_scale : float, optional
        Multiplicative factor applied to the natural covalent cutoffs.

    Returns
    -------
    list of tuples
        Each tuple contains:

        (atom_i, atom_j, equilibrium_distance)

        Each pair appears only once.
    """

    if len(atoms) == 0:
        return []

    particle = atoms.copy()

    # NanoAmorphizer works with finite nanoparticles.
    particle.set_pbc(False)

    cutoffs = natural_cutoffs(
        particle,
        mult=cutoff_scale,
    )

    neighbor_list = NeighborList(
        cutoffs,
        skin=0.0,
        self_interaction=False,
        bothways=True,
    )

    neighbor_list.update(particle)

    positions = particle.get_positions()

    network = []
    seen_pairs = set()

    for i in range(len(particle)):

        indices, _ = neighbor_list.get_neighbors(i)

        for j in indices:

            j = int(j)

            if i == j:
                continue

            pair = tuple(sorted((i, j)))

            if pair in seen_pairs:
                continue

            seen_pairs.add(pair)

            vector = positions[pair[1]] - positions[pair[0]]
            distance = np.linalg.norm(vector)

            network.append(
                (
                    pair[0],
                    pair[1],
                    float(distance),
                )
            )

    return network


def get_coordination_numbers(
    atoms,
    neighbor_network,
):
    """
    Calculate the coordination number of every atom.

    Parameters
    ----------
    atoms : ase.Atoms
        Nanoparticle.

    neighbor_network : list
        Neighbor network generated by build_neighbor_network().

    Returns
    -------
    numpy.ndarray
        Coordination number for every atom.
    """

    coordination = np.zeros(
        len(atoms),
        dtype=int,
    )

    for i, j, _ in neighbor_network:

        coordination[i] += 1
        coordination[j] += 1

    return coordination


def get_nearest_neighbor_distances(
    atoms,
    neighbor_network,
):
    """
    Calculate the shortest first-neighbor distance for every atom.

    Atoms without detected neighbors are returned as NaN.
    """

    nearest = np.full(
        len(atoms),
        np.nan,
        dtype=float,
    )

    for i, j, distance in neighbor_network:

        if np.isnan(nearest[i]) or distance < nearest[i]:
            nearest[i] = distance

        if np.isnan(nearest[j]) or distance < nearest[j]:
            nearest[j] = distance

    return nearest


def get_characteristic_neighbor_distance(
    atoms,
    neighbor_network=None,
    cutoff_scale=1.20,
):
    """
    Estimate a characteristic nearest-neighbor distance.

    The median shortest-neighbor distance is used to reduce the
    influence of surface atoms and unusual local environments.

    Returns
    -------
    float
        Characteristic nearest-neighbor distance in angstroms.
    """

    if neighbor_network is None:

        neighbor_network = build_neighbor_network(
            atoms,
            cutoff_scale=cutoff_scale,
        )

    nearest = get_nearest_neighbor_distances(
        atoms,
        neighbor_network,
    )

    valid = nearest[
        np.isfinite(nearest)
    ]

    if len(valid) == 0:

        raise ValueError(
            "No first-neighbor distances could be identified."
        )

    return float(
        np.median(valid)
    )


def get_neighbor_map(
    atoms,
    neighbor_network,
):
    """
    Return the neighbor indices associated with every atom.

    This map will later be used to identify local structural units,
    including tetrahedral coordination.
    """

    neighbor_map = [
        [] for _ in range(len(atoms))
    ]

    for i, j, _ in neighbor_network:

        neighbor_map[i].append(j)
        neighbor_map[j].append(i)

    return neighbor_map


def get_neighbor_summary(
    atoms,
    neighbor_network=None,
    cutoff_scale=1.20,
):
    """
    Return a compact summary of the local neighbor network.
    """

    if neighbor_network is None:

        neighbor_network = build_neighbor_network(
            atoms,
            cutoff_scale=cutoff_scale,
        )

    coordination = get_coordination_numbers(
        atoms,
        neighbor_network,
    )

    characteristic_distance = (
        get_characteristic_neighbor_distance(
            atoms,
            neighbor_network=neighbor_network,
        )
    )

    coordinated_atoms = coordination[
        coordination > 0
    ]

    if len(coordinated_atoms) > 0:

        median_coordination = float(
            np.median(coordinated_atoms)
        )

    else:

        median_coordination = 0.0

    return {
        "neighbor_pairs": len(neighbor_network),
        "characteristic_distance_A": characteristic_distance,
        "median_coordination": median_coordination,
    }